/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DjalalxJay (https://sketchfab.com/djalalxjay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-satellite-low-poly-free-f23b484cda664f1cb91b4f62ea5ef8bf
Title: Simple Satellite Low Poly Free
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import birdScene from "../assets/3d/bird.glb";
import { useRef, useEffect } from "react";
import { useFrame } from "@react-three/fiber";

import satellite from "../assets/3d/satellite.glb";

export const Satellite = (props) => {
  const { nodes, materials } = useGLTF(satellite);
  const ref = useRef();

  //   const { scene, animations } = useGLTF(birdScene);
  //   const { actions } = useAnimations(animations, ref);

  //   useEffect(() => {
  //     actions["Take 001"].play();
  //   });

  useFrame(({ clock, camera }) => {
    ref.current.position.y = Math.sin(clock.elapsedTime) * 0.2 + 2;

    if (ref.current.position.x > camera.position.x + 10) {
      ref.current.rotation.y = Math.PI;
    } else if (ref.current.position.x < camera.position.x - 10) {
      ref.current.rotation.y = 0;
    }

    if (ref.current.rotation.y === 0) {
      ref.current.position.x += 0.01;
      ref.current.position.z -= 0.01;
    } else {
      ref.current.position.x -= 0.01;
      ref.current.position.z += 0.01;
    }
  });
  return (
    <group ref={ref} position={[-5, 2, 1]} scale={[0.5, 0.5, 0.5]}>
      <group rotation={[-1.755, 0.06, 2.589]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0.186]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.875, 0.883, 0.875]}>
            <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.Satellite} />
            <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.Gold} />
            <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.Satellite_2} />
          </group>
          <group rotation={[0, 0, 0.137]} scale={0.075}>
            <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials.Satellite} />
            <mesh castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials.Gold} />
          </group>
          <group position={[0, 0, 2.294]} rotation={[0, 0, -0.402]} scale={0.075}>
            <mesh castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials.Satellite} />
            <mesh castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials.Gold} />
          </group>
          <group position={[0, 0, 3.53]} rotation={[0, 0, 0.995]} scale={0.06}>
            <mesh castShadow receiveShadow geometry={nodes.Object_28.geometry} material={materials.Satellite} />
            <mesh castShadow receiveShadow geometry={nodes.Object_29.geometry} material={materials.Gold} />
          </group>
          <group position={[0, 0, 2.575]}>
            <mesh castShadow receiveShadow geometry={nodes.Object_55.geometry} material={materials.Satellite} />
            <mesh castShadow receiveShadow geometry={nodes.Object_56.geometry} material={materials.Solar_Panel} />
          </group>
          <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.Satellite} position={[0, 0, 1.395]} />
          <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.Satellite} position={[0, 0, 1.781]} />
          <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.Satellite} position={[0, 0, 0.519]} />
          <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials.Satellite} position={[0, 0, 1.584]} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_16.geometry}
            material={materials.Gold}
            position={[0, -0.018, 1.821]}
            rotation={[0, 0, 0.021]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_24.geometry}
            material={materials.Packs}
            position={[0, 0, 2.699]}
            rotation={[0, 0, -0.481]}
          />
          <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials.Packs} position={[0, 0, 2.127]} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_31.geometry}
            material={materials.Satellite}
            position={[0, 0, 2.831]}
            rotation={[0, 0, -0.811]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_33.geometry}
            material={materials.Packs}
            position={[0, 0, 3.04]}
            rotation={[0, 0, 1.475]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_35.geometry}
            material={materials.Packs}
            position={[0, 0, 3.277]}
            rotation={[0, 0, 1.475]}
          />
          <mesh castShadow receiveShadow geometry={nodes.Object_37.geometry} material={materials.Gold} />
          <mesh castShadow receiveShadow geometry={nodes.Object_39.geometry} material={materials.Gold} position={[0, 0, 1.332]} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_41.geometry}
            material={materials.Gold}
            position={[0, 0, 2.78]}
            rotation={[0, 0, 1.397]}
            scale={0.803}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_43.geometry}
            material={materials.Satellite}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={1.465}
          />
          <mesh castShadow receiveShadow geometry={nodes.Object_45.geometry} material={materials.Satellite} rotation={[0, Math.PI / 2, 0]} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_47.geometry}
            material={materials.Satellite}
            position={[0, 0, -0.508]}
            rotation={[Math.PI / 2, Math.PI / 4, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_49.geometry}
            material={materials.Satellite}
            position={[0, 0, -1.248]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_51.geometry}
            material={materials.Satellite}
            position={[0, 0, -1.237]}
            rotation={[Math.PI / 2, Math.PI / 4, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_53.geometry}
            material={materials.Satellite}
            position={[0, 0, -1.237]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
        </group>
      </group>
    </group>
  );
};
